### ISSUE TITLE
Enviar o questionário respondido (candidato)

### ISSUE THREAD

**Issue by nicolasiensen** [meurio/verdade-ou-consequencia#37]

**Comment by luizfonseca** [comment]
#sdds @nicolasiensen

**Comment by luizfonseca** [comment]
#sdds

*Luiz Fonseca*
Entrepreneur and Software Developer
http://about.luiz.cc | http://blog.luiz.cc
@github <http://github.com/luizfonseca> / @twitter
<http://twitter.com/runeroniek> / @facebook
<https://www.facebook.com/luizfonseca.cc>
+55 21 9 9713 7471

**Comment by nicolasiensen** [comment]
Bons tempos!
